"""Write docs/DEMO.md: the 2-minute demo script, with ids and numbers read from web/public/data."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
D = ROOT / "web" / "public" / "data"


def load(name):
    p = D / name
    return json.loads(p.read_text()) if p.exists() else None


def main() -> None:
    idx, briefs, results, about = load("index.json"), load("briefs.json") or [], load("results.json") or {}, load("about.json") or {}
    if not idx or not idx["runs"]:
        raise SystemExit("no export yet: run `make export` first")
    top = briefs[0] if briefs else None
    run_id = (top or {}).get("run_id") or idx["runs"][0]["run_id"]
    run = json.loads((D / "runs" / f"{run_id}.json").read_text())
    trials = run["trials"]
    best = sorted(trials, key=lambda t: ["misreading", "known_answer", "rebutted", "revision_required",
                                         "standing"].index(t["outcome"]) if t.get("outcome") else -1)[-1] if trials else None
    obj = next((o for o in run["objections"] if best and o["id"] == best["objection_id"]), None)
    nov = run["novelty"].get(best["objection_id"], {}) if best else {}
    e1, e2, e3 = results.get("e1"), results.get("e2"), results.get("e3")
    corpus = about.get("corpus", {})
    L = ["# Demo script (2 minutes)", "",
         "Generated by `scripts/make_demo_md.py` from `web/public/data/` — every id and number below is read from the export.",
         f"Export generated at {idx['generated_at']}.", "",
         "Start: `make demo` → http://localhost:4680", "",
         "## 0:00 — The problem (landing page `/`)",
         "- Say: *Philosophers need to know where the open questions are. Crux Lab is a research lab in which AI agents "
         "run the experiment philosophy actually has: the debate.*",
         "- Point at the three numbers: " + "; ".join(f"**{h['value']}** {h['label']}" for h in idx["headline"]) + ".",
         f"- Corpus: {corpus.get('records', '?')} OpenAlex records ({corpus.get('distinct_works', '?')} distinct works), "
         f"{corpus.get('full_texts', '?')} open-access full texts, "
         f"{corpus.get('fresh', '?')} published since 2026-08-01.", "",
         f"## 0:20 — A research direction (`/brief/{top['id']}`)" if top else "## 0:20 — Briefs (`/briefs`)"]
    if top:
        L += [f"- Research question: *{top['research_question']}*",
              f"- Outcome **{top['outcome']}**, novelty {top['novelty']:.2f} over {top['records_searched']} records searched. "
              "Point at the three nearest matches and the line *Further human review required.*",
              f"- Challenged premise `{top['challenged_premise']['id']}`: {top['challenged_premise']['text']}"]
        if top.get("assessment"):
            q = top["assessment"]
            L += [f"- Click **Referee's assessment** (bottom of the brief): the Assessor first graded it *{q['grade']}* "
                  f"({q['overall']}/5): \"{q['summary'][:180]}\""]
            r = (top.get("revision") or {}).get("assessment")
            if r:
                L += [f"- Then the **revision round**: rewritten to answer that objection, it was re-graded in a fresh read "
                      f"as *{r['grade']}* ({r['overall']}/5). Say: *the lab argues with its own leads before it hands "
                      f"them to you.*"]
        L += [""]
    L += [f"## 0:45 — How it got there (`/lab/{run_id}`)",
          f"- Target: *{run['target']['title']}* ({run['target'].get('kind')}, {run['target'].get('published') or run['target'].get('year')}).",
          f"- Left: the argument map; the Formalizer's hidden premise `{run['argument'].get('missing_premise_id')}` is highlighted "
          f"(skeleton `{run['argument']['skeleton']}`, {'valid' if run['argument']['valid'] else 'invalid as stated'}).",
          f"- Press play: {len(run['objections'])} objections from {', '.join(run['families_used'])} models, "
          f"{len(trials)} trials. Right: the Director queue reorders after each step ({len(run['director_steps'])} steps).", ""]
    if best and obj:
        L += [f"## 1:10 — One trial (`/trial/{best['id']}`)",
              f"- Objection by **{obj['agent']}** ({obj['family']}:{obj['model']}) against `{obj['target_premise_id']}`.",
              f"- Novelty {nov.get('novelty', 0):.2f}; nearest: " + "; ".join(
                  f"{m['verdict']} — {m['title'][:60]}" for m in nov.get("nearest", [])[:2]) + ".",
              "- Show Defender A (firm) and Defender B (concessive, other family), the objector's rejoinder, "
              f"and the Referee's label: **{best['outcome']}** — \"{best['deciding_quote'][:160]}\"", ""]
    L += ["## 1:35 — Does it work? (`/results`)"]
    if e1:
        L.append("- E1 prior-art recall@5 (n=%d): " % e1["n"] + "; ".join(f"{m['name']} {m['recall_at_5']:.0%}" for m in e1["methods"]) + ".")
    if e2:
        L.append(f"- E2 calibration: {e2['known_answer']['correct_reply_cited']}/{e2['known_answer']['n']} published objections "
                 f"labelled known_answer with the right reply cited, but a defender cited a verified gold reply in "
                 f"{e2['known_answer'].get('gold_reply_cited_by_a_defender', '?')}/{e2['known_answer']['n']} (the Referee is conservative); "
                 f"{e2['misreading']['caught']}/{e2['misreading']['n']} deliberate misreadings caught.")
    if e3:
        L.append("- E3 diversity: " + "; ".join(f"{c['name']}: {c['distinct_premises']} distinct premises, novelty>0.5 share {c['share_novelty_gt_05']:.0%}" for c in e3["conditions"]) + ".")
    L += ["- Read the limits line aloud: the numbers are small and the lab says so.", "",
          "## 1:45 — Any topic (`/topics`, `/start`)",
          "- Topics lists what has been run (divine hiddenness) and what is set up (the fine-tuning argument); "
          "Start a topic writes a student's own topic file and the exact commands to run the lab on it.", "",
          "## 1:55 — Close (`/about`)",
          f"- Model families: {about.get('diversity', '?')}. Databricks: MLflow tracing, Model Serving provider, "
          "claims Delta table + AI Search Delta Sync index (wired; runs when workspace credentials are set).",
          "- Say: *The lab never claims novelty. It tells a philosopher where to look, and shows its work.*", ""]
    (ROOT / "docs" / "DEMO.md").write_text("\n".join(L))
    print("wrote docs/DEMO.md")


if __name__ == "__main__":
    main()
