"""`make export`: everything the static site shows, written to web/public/data/.

Files: index.json · runs/<run_id>.json · briefs.json · briefs/<id>.json · records.json ·
claims.json · results.json · about.json. Only data generated by this repo's code goes here.
"""
from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone

from crux_lab.config import BRIEFS, CONFIG, DATA, RESOLVED_MODELS, RESULTS, RUNS, TARGETS, WEB_DATA
from crux_lab.corpus.build import load_corpus
from crux_lab.graph.schema import SURVIVAL, Argument, Claim
from crux_lab.graph.store import Store


def _read(p):
    return json.loads(p.read_text()) if p.exists() else None


def _record(p: dict) -> dict:
    return {"id": p["id"], "title": p.get("title", ""), "authors": p.get("authors", [])[:6],
            "year": p.get("year"), "url": p.get("url") or "", "venue": p.get("venue"),
            "abstract": (p.get("abstract") or "")[:1800], "source": p.get("source"),
            "fresh": bool(p.get("fresh")), "published": p.get("publication_date")}


def paper_of_claim(cid: str) -> str:
    return cid.split(".", 1)[0]


def main() -> dict:
    out = WEB_DATA
    if out.exists():
        for sub in ("runs", "briefs"):
            d = out / sub
            if d.exists():
                shutil.rmtree(d)
    (out / "runs").mkdir(parents=True, exist_ok=True)
    (out / "briefs").mkdir(parents=True, exist_ok=True)
    corpus = load_corpus()
    papers = {p["id"]: p for p in corpus}
    short = {p["id"].split(":", 1)[-1]: p["id"] for p in corpus}
    store = Store()
    needed: set[str] = set()

    runs_summary = []
    for f in sorted(RUNS.glob("run-*.json")):
        run = json.loads(f.read_text())
        needed.add(run["target"]["paper_id"])
        for n in run.get("novelty", {}).values():
            for m in n.get("matches", []):
                needed.add(m["paper_id"])
        for t in run.get("trials", []):
            for cid in t.get("cited_claim_ids", []):
                if paper_of_claim(cid) in short:
                    needed.add(short[paper_of_claim(cid)])
        (out / "runs" / f.name).write_text(json.dumps(run, ensure_ascii=False))
        outcomes: dict[str, int] = {}
        for t in run.get("trials", []):
            k = t.get("outcome") or "failed"
            outcomes[k] = outcomes.get(k, 0) + 1
        runs_summary.append({
            "run_id": run["run_id"], "target_id": run["target"]["id"], "kind": run["target"].get("kind"),
            "title": run["target"]["title"], "paper_id": run["target"]["paper_id"],
            "argument_title": run["argument"].get("title"), "objections": len(run.get("objections", [])),
            "trials": len(run.get("trials", [])), "outcomes": outcomes, "briefs": run.get("briefs", []),
            "families": run.get("families_used", []), "stop_reason": run.get("stop_reason"),
            "finished_at": run.get("finished_at")})

    briefs = []
    for f in sorted(BRIEFS.glob("brief-*.json")):
        b = json.loads(f.read_text())
        (out / "briefs" / f.name).write_text(json.dumps(b, ensure_ascii=False))
        md = f.with_suffix(".md")
        if md.exists():
            (out / "briefs" / md.name).write_text(md.read_text())
        for c in b.get("closest_literature", []):
            if c.get("paper_id"):
                needed.add(c["paper_id"])
        run_id = next((r["run_id"] for r in runs_summary if b["id"] in r["briefs"]), None)
        briefs.append({"id": b["id"], "run_id": run_id, "research_question": b["research_question"],
                       "outcome": b.get("outcome"), "novelty": b["novelty"],
                       "records_searched": b["records_searched"],
                       "survival": SURVIVAL.get(b.get("outcome") or "", 0),
                       "paper_title": b["argument"].get("paper_title"),
                       "challenged_premise": b["challenged_premise"],
                       "paper_direction": b["paper_direction"]})
    briefs.sort(key=lambda b: -(b["survival"] * b["novelty"]))
    (out / "briefs.json").write_text(json.dumps(briefs, ensure_ascii=False, indent=1))

    # claims + edges for the atlas (embeddings dropped)
    claims = [c.model_dump(exclude={"embedding"}) for c in store.all(Claim)]
    for c in claims:
        needed.add(c["paper_id"])
    args = [a.model_dump() for a in store.all(Argument)]
    edges = [e.model_dump() for e in store.edges()]
    (out / "claims.json").write_text(json.dumps({"claims": claims, "arguments": args, "edges": edges},
                                                ensure_ascii=False))
    records = {pid: _record(papers[pid]) for pid in sorted(needed) if pid in papers}
    (out / "records.json").write_text(json.dumps(records, ensure_ascii=False))

    results = {k: _read(RESULTS / f"{k}.json") for k in ("e1", "e2", "e3")}
    (out / "results.json").write_text(json.dumps(results, ensure_ascii=False, indent=1))
    resolved = _read(RESOLVED_MODELS) or {}
    targets = _read(TARGETS) or {}
    map_stats = _read(DATA / "map_stats.json") or {}
    about = {
        "diversity": resolved.get("diversity"), "families": resolved.get("families", []),
        "roles": resolved.get("roles", {}),
        "models": [{k: m[k] for k in ("provider", "model", "family", "ok")} for m in resolved.get("models", [])],
        "targets_meta": targets.get("meta", {}),
        "map_stats": {k: map_stats.get(k) for k in ("fulltext_claims", "abstract_claims", "claims_indexed",
                                                   "abstracts_indexed", "embedder")},
        "corpus": {"records": len(corpus), "with_abstract": sum(1 for p in corpus if p.get("abstract")),
                   "full_texts": sum(1 for p in corpus if p.get("pdf_path")),
                   "fresh": sum(1 for p in corpus if p.get("fresh"))},
    }
    (out / "about.json").write_text(json.dumps(about, ensure_ascii=False, indent=1))
    index = {"generated_at": datetime.now(timezone.utc).isoformat(), "runs": runs_summary,
             "targets": targets.get("targets", []), "briefs": len(briefs),
             "trials": sum(r["trials"] for r in runs_summary),
             "objections": sum(r["objections"] for r in runs_summary),
             "headline": headline(results, runs_summary, briefs)}
    (out / "index.json").write_text(json.dumps(index, ensure_ascii=False, indent=1))
    print(f"exported {len(runs_summary)} runs, {len(briefs)} briefs, {len(claims)} claims, "
          f"{len(records)} records -> {out}")
    return index


def headline(results: dict, runs: list[dict], briefs: list[dict]) -> list[dict]:
    """Three landing-page numbers, each computed from files (never typed in by hand)."""
    h = []
    trials = sum(r["trials"] for r in runs)
    surv = sum(r["outcomes"].get("standing", 0) + r["outcomes"].get("revision_required", 0) for r in runs)
    if trials:
        h.append({"label": "objections still standing or forcing a revision after both defenders",
                  "value": f"{surv}/{trials}", "source": "data/runs"})
    e1 = results.get("e1") or {}
    if e1.get("methods"):
        best = max(e1["methods"], key=lambda m: m.get("recall_at_5", 0))
        h.append({"label": f"prior-art recall@5 ({best['name']})", "value": f"{best['recall_at_5']:.0%}",
                  "source": "results/e1.json"})
    e2 = results.get("e2") or {}
    if e2.get("misreading", {}).get("n"):
        h.append({"label": "deliberate misreadings caught by the Referee",
                  "value": f"{e2['misreading']['caught']}/{e2['misreading']['n']}", "source": "results/e2.json"})
    if len(h) < 3 and briefs:
        h.append({"label": "research briefs ready for human review", "value": str(len(briefs)),
                  "source": "data/briefs"})
    return h[:3]
