"""`make export`: everything the static site shows, written to web/public/data/.

Files: index.json · runs/<run_id>.json · briefs.json · briefs/<id>.json · records.json ·
claims.json · results.json · about.json. Only data generated by this repo's code goes here.
"""
from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone

from crux_lab.config import BRIEFS, DATA, RESOLVED_MODELS, RESULTS, RUNS, TARGETS, WEB_DATA
from crux_lab.corpus.build import load_corpus
from crux_lab.corpus.dedup import work_ids
from crux_lab.graph.schema import SURVIVAL, Argument, Claim
from crux_lab.graph.store import Store


METHOD_NOTES = [
    "Generators never see literature: their context builder only receives the argument's own premises "
    "(enforced by construction and by a test that inspects the module's imports).",
    "Every extracted claim carries a verbatim quote (at most two sentences) found in the source text "
    "(rapidfuzz partial_ratio >= 90); claims whose quote cannot be found are dropped.",
    "Citations are corpus claim ids only. Code verifies each cited id (it exists and the defender was shown it, "
    "or it belongs to the argument's own paper) and strikes the rest; known_answer requires a verified literature id.",
    "The Formalizer's validity verdicts come from a truth table in code, not from the model; a proposed missing "
    "premise is kept only if the re-check makes the argument valid without making the premises inconsistent.",
    "After a trial ends in revision_required, the revised premise joins the argument: later trials in the same run "
    "test the revised argument, and one new objection attacks the revised premise (depth at most 2).",
    "The objection keeps the outcome most favourable to the original argument across the two defenders, "
    "so an outcome of revision_required means both defenders needed a premise change.",
    "Blind generators run in parallel and are each assigned a different stated premise for coverage; the "
    "Hidden-Premise Attacker always targets the Formalizer's missing premise.",
    "Subscription CLI providers (codex, claude -p) ignore temperature; diversity comes from different models and roles.",
    "Novelty is never claimed: it is 1 - max similarity among same_move/related matches in what retrieval found, "
    "reported with records searched, the three nearest matches and 'Further human review required.'",
]


def rank_directions(briefs: list[dict]) -> list[dict]:
    """Survival × novelty, but round-robin across runs so the top of the list shows breadth:
    every target's best direction first, then every target's second best, and so on."""
    for b in briefs:
        b["score"] = round(b["survival"] * b["novelty"], 4)
    by_run: dict = {}
    for b in sorted(briefs, key=lambda b: -b["score"]):
        by_run.setdefault(b["run_id"], []).append(b)
    out, rnd = [], 0
    while any(by_run.values()):
        tier = [lst.pop(0) for lst in by_run.values() if lst]
        for b in sorted(tier, key=lambda b: -b["score"]):
            b["tier"] = rnd
            out.append(b)
        rnd += 1
    return out


def tracing_summary() -> dict:
    """How many LLM calls were traced with MLflow (local sqlite store unless Databricks was configured)."""
    import sqlite3

    from crux_lab.config import ROOT
    from crux_lab.config import settings
    db = ROOT / "mlruns" / "mlflow.db"
    out = {"backend": "databricks" if settings.has("databricks") else "local MLflow (mlruns/)", "traces": None}
    if db.exists():
        try:
            out["traces"] = sqlite3.connect(db).execute("select count(*) from trace_info").fetchone()[0]
        except sqlite3.Error:
            pass
    return out


def _read(p):
    return json.loads(p.read_text()) if p.exists() else None


def _record(p: dict) -> dict:
    return {"id": p["id"], "title": p.get("title", ""), "authors": p.get("authors", [])[:6],
            "year": p.get("year"), "url": p.get("url") or "", "venue": p.get("venue"),
            "abstract": (p.get("abstract") or "")[:1800], "source": p.get("source"),
            "fresh": bool(p.get("fresh")), "published": p.get("publication_date")}


def paper_of_claim(cid: str) -> str:
    return cid.split(".", 1)[0]


def main() -> dict:
    out = WEB_DATA
    if Store().count(Claim) == 0:
        # A fresh clone has the committed export but not the (gitignored) claim store: never overwrite
        # the committed site data with an empty graph.
        raise SystemExit("export: the claim store (data/crux.sqlite) is empty — run `make map` first. "
                         "The committed web/public/data was left untouched.")
    if out.exists():
        for sub in ("runs", "briefs"):
            d = out / sub
            if d.exists():
                shutil.rmtree(d)
    (out / "runs").mkdir(parents=True, exist_ok=True)
    (out / "briefs").mkdir(parents=True, exist_ok=True)
    corpus = load_corpus()
    papers = {p["id"]: p for p in corpus}
    short = {p["id"].split(":", 1)[-1]: p["id"] for p in corpus}
    store = Store()
    needed: set[str] = set()

    runs_summary = []
    for f in sorted(RUNS.glob("run-*.json")):
        run = json.loads(f.read_text())
        needed.add(run["target"]["paper_id"])
        for n in run.get("novelty", {}).values():
            for m in n.get("matches", []):
                needed.add(m["paper_id"])
        for t in run.get("trials", []):
            for cid in t.get("cited_claim_ids", []):
                if paper_of_claim(cid) in short:
                    needed.add(short[paper_of_claim(cid)])
        (out / "runs" / f.name).write_text(json.dumps(run, ensure_ascii=False))
        outcomes: dict[str, int] = {}
        for t in run.get("trials", []):
            k = t.get("outcome") or "failed"
            outcomes[k] = outcomes.get(k, 0) + 1
        runs_summary.append({
            "run_id": run["run_id"], "target_id": run["target"]["id"], "kind": run["target"].get("kind"),
            "title": run["target"]["title"], "paper_id": run["target"]["paper_id"],
            "argument_title": run["argument"].get("title"), "objections": len(run.get("objections", [])),
            "trials": len(run.get("trials", [])), "outcomes": outcomes, "briefs": run.get("briefs", []),
            "families": run.get("families_used", []), "stop_reason": run.get("stop_reason"),
            "finished_at": run.get("finished_at")})

    briefs = []
    for f in sorted(BRIEFS.glob("brief-*.json")):
        b = json.loads(f.read_text())
        (out / "briefs" / f.name).write_text(json.dumps(b, ensure_ascii=False))
        md = f.with_suffix(".md")
        if md.exists():
            (out / "briefs" / md.name).write_text(md.read_text())
        for c in b.get("closest_literature", []):
            if c.get("paper_id"):
                needed.add(c["paper_id"])
        run_id = next((r["run_id"] for r in runs_summary if b["id"] in r["briefs"]), None)
        briefs.append({"id": b["id"], "run_id": run_id, "research_question": b["research_question"],
                       "outcome": b.get("outcome"), "novelty": b["novelty"],
                       "records_searched": b["records_searched"],
                       "survival": SURVIVAL.get(b.get("outcome") or "", 0),
                       "paper_title": b["argument"].get("paper_title"),
                       "challenged_premise": b["challenged_premise"],
                       "paper_direction": b["paper_direction"]})
    briefs = rank_directions(briefs)
    (out / "briefs.json").write_text(json.dumps(briefs, ensure_ascii=False, indent=1))

    # claims + edges for the atlas (embeddings dropped)
    from crux_lab.corpus.dedup import work_of
    claims = [c.model_dump(exclude={"embedding"}) for c in store.all(Claim)]
    for c in claims:
        needed.add(c["paper_id"])
        c["work"] = work_of(c["paper_id"])   # same paper listed twice in OpenAlex -> same work
    args = [a.model_dump() for a in store.all(Argument)]
    edges = [e.model_dump() for e in store.edges()]
    (out / "claims.json").write_text(json.dumps({"claims": claims, "arguments": args, "edges": edges},
                                                ensure_ascii=False))
    live = {}
    from crux_lab.lab.novelty import LIVE_CACHE
    for f in LIVE_CACHE.glob("*.json") if LIVE_CACHE.exists() else []:
        for w in json.loads(f.read_text()):
            live.setdefault(w["id"], {**w, "source": "openalex_live"})
    records = {pid: _record(papers.get(pid) or live[pid]) for pid in sorted(needed) if pid in papers or pid in live}
    (out / "records.json").write_text(json.dumps(records, ensure_ascii=False))
    # Slim title index for /atlas (it shows titles and years only; the record drawer loads records.json).
    titles = {pid: {"id": pid, "title": r["title"], "year": r["year"]} for pid, r in records.items()}
    (out / "titles.json").write_text(json.dumps(titles, ensure_ascii=False, separators=(",", ":")))

    results = {k: _read(RESULTS / f"{k}.json") for k in ("e1", "e2", "e3")}
    (out / "results.json").write_text(json.dumps(results, ensure_ascii=False, indent=1))
    resolved = _read(RESOLVED_MODELS) or {}
    targets = _read(TARGETS) or {}
    map_stats = _read(DATA / "map_stats.json") or {}
    about = {
        "diversity": resolved.get("diversity"), "families": resolved.get("families", []),
        "roles": resolved.get("roles", {}),
        "models": [{k: m[k] for k in ("provider", "model", "family", "ok")} for m in resolved.get("models", [])],
        "targets_meta": targets.get("meta", {}),
        "map_stats": {k: map_stats.get(k) for k in ("fulltext_claims", "abstract_claims", "claims_indexed",
                                                   "abstracts_indexed", "embedder")},
        "corpus": {"records": len(corpus), "distinct_works": len(set(work_ids(corpus).values())),
                   "with_abstract": sum(1 for p in corpus if p.get("abstract")),
                   "full_texts": sum(1 for p in corpus if p.get("pdf_path")),
                   "fresh": sum(1 for p in corpus if p.get("fresh"))},
    }
    tot: dict[str, int] = {}
    for r in runs_summary:
        for k, v in r["outcomes"].items():
            tot[k] = tot.get(k, 0) + v
    never = [o for o in ("rebutted", "standing", "known_answer") if not tot.get(o)]
    skew = ("Outcome distribution across all trials: " + ", ".join(f"{k} {v}" for k, v in sorted(tot.items(), key=lambda kv: -kv[1]))
            + (f". No trial ended {' or '.join(never)}: defenders usually save the argument by narrowing a premise, "
               "which counts as revision_required, so read it as 'this premise needs work', not as a defeated argument."
               if never else "."))
    n_works = len(set(work_ids(corpus).values()))
    dup_note = (f"OpenAlex lists some papers more than once (versions, preprint + article): the {len(corpus)} corpus "
                f"records are {n_works} distinct works. 'Records searched' counts records; nearest matches, the "
                "prior-art search box and E1 are scored per distinct work.")
    about["method_notes"] = METHOD_NOTES + ([skew] if tot else []) + [dup_note]
    about["tracing"] = tracing_summary()
    (out / "about.json").write_text(json.dumps(about, ensure_ascii=False, indent=1))
    index = {"generated_at": datetime.now(timezone.utc).isoformat(), "runs": runs_summary,
             "targets": targets.get("targets", []), "briefs": len(briefs),
             "trials": sum(r["trials"] for r in runs_summary),
             "objections": sum(r["objections"] for r in runs_summary),
             "headline": headline(results, runs_summary, briefs)}
    (out / "index.json").write_text(json.dumps(index, ensure_ascii=False, indent=1))
    print(f"exported {len(runs_summary)} runs, {len(briefs)} briefs, {len(claims)} claims, "
          f"{len(records)} records -> {out}")
    return index


def headline(results: dict, runs: list[dict], briefs: list[dict]) -> list[dict]:
    """Three landing-page numbers, each computed from files (never typed in by hand)."""
    h = []
    trials = sum(r["trials"] for r in runs)
    surv = sum(r["outcomes"].get("standing", 0) + r["outcomes"].get("revision_required", 0) for r in runs)
    if trials:
        h.append({"label": "objections still standing or forcing a revision after both defenders",
                  "value": f"{surv}/{trials}", "source": "data/runs"})
    e1 = results.get("e1") or {}
    if e1.get("methods"):
        best = max(e1["methods"], key=lambda m: m.get("recall_at_5", 0))
        h.append({"label": f"prior-art recall@5 ({best['name']})", "value": f"{best['recall_at_5']:.0%}",
                  "source": "results/e1.json"})
    e2 = results.get("e2") or {}
    if e2.get("misreading", {}).get("n"):
        h.append({"label": "deliberate misreadings caught by the Referee",
                  "value": f"{e2['misreading']['caught']}/{e2['misreading']['n']}", "source": "results/e2.json"})
    if len(h) < 3 and briefs:
        h.append({"label": "research briefs ready for human review", "value": str(len(briefs)),
                  "source": "data/briefs"})
    return h[:3]
