"""`make export`: everything the static site shows, written to web/public/data/.

Files: index.json · runs/<run_id>.json · briefs.json · briefs/<id>.json · records.json ·
claims.json · results.json · about.json. Only data generated by this repo's code goes here.
"""
from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone

from crux_lab.config import (BRIEFS, DEFAULT_TOPIC, MAP_STATS, RESOLVED_MODELS, TOPIC_RESOLVED, RESULTS, RUNS, TARGETS, TOPIC,
                             TOPIC_SLUG, TOPICS, WEB_DATA, WEB_DATA_ROOT, topic_paths)
from crux_lab.corpus.build import load_corpus
from crux_lab.corpus.dedup import work_ids
from crux_lab.graph.schema import SURVIVAL, Argument, Claim
from crux_lab.graph.store import Store


METHOD_NOTES = [
    "Generators never see literature: their context builder only receives the argument's own premises "
    "(enforced by construction and by a test that inspects the module's imports).",
    "Every extracted claim carries a verbatim quote (at most two sentences) found in the source text "
    "(rapidfuzz partial_ratio >= 90); claims whose quote cannot be found are dropped.",
    "Citations are corpus claim ids only. Code verifies each cited id (it exists and the defender was shown it, "
    "or it belongs to the argument's own paper) and strikes the rest; known_answer requires a verified literature id.",
    "The Formalizer's validity verdicts come from a truth table in code, not from the model; a proposed missing "
    "premise is kept only if the re-check makes the argument valid without making the premises inconsistent.",
    "After a trial ends in revision_required, the revised premise joins the argument: later trials in the same run "
    "test the revised argument, and one new objection attacks the revised premise (depth at most 2).",
    "The objection keeps the outcome most favourable to the original argument across the two defenders, "
    "so an outcome of revision_required means both defenders needed a premise change.",
    "Blind generators run in parallel and are each assigned a different stated premise for coverage; the "
    "Hidden-Premise Attacker always targets the Formalizer's missing premise.",
    "Subscription CLI providers (codex, claude -p) ignore temperature; diversity comes from different models and roles.",
    "Novelty is never claimed: it is 1 - max similarity among same_move/related matches in what retrieval found, "
    "reported with records searched, the three nearest matches and 'Further human review required.'",
    "Every research direction is graded by an Assessor agent from a different model family than the brief writer, "
    "acting as a journal referee; the grade (promising / needs work / not yet defensible) is computed in code from "
    "its four 1-5 scores, and a direction that falls to an obvious objection is never 'promising'.",
    "Research directions are ranked by lead score = survival x novelty x quality, where quality is the Assessor's "
    "latest overall score / 5 (after the revision round if there was one): a direction leads only if it survived the "
    "defenders, nothing close to it was found, and the Assessor found it sound.",
]


def topic_commands(slug: str) -> list[str]:
    t = "" if slug == DEFAULT_TOPIC else f" TOPIC={slug}"
    return [f"make corpus{t}", f"make targets{t}", f"make map{t}", f"make runs{t}", f"make assess{t}",
            f"make revise{t}", f"make eval{t}", f"make export{t}"]


def write_topics_index() -> dict:
    """web/public/data/topics.json: every configured topic, whether it has been run and exported, and how
    to run it. Written on every export, whichever topic is being exported."""
    topics = []
    for slug, t in TOPICS.items():
        web = topic_paths(slug)["web"]
        idx = _read(web / "index.json") if (web / "index.json").exists() else None
        ab = _read(web / "about.json") if (web / "about.json").exists() else None
        br = _read(web / "briefs.json") if (web / "briefs.json").exists() else None
        ready = bool(idx and idx.get("runs"))
        lead = br[0] if ready and br else None
        topics.append({
            "slug": slug, "name": t.get("name", slug), "description": t.get("description", ""),
            "area": t.get("area", ""), "default": slug == DEFAULT_TOPIC,
            "status": "ready" if ready else "not_run",
            "data": "" if slug == DEFAULT_TOPIC else f"topics/{slug}/",
            "counts": ({"papers": len(idx["runs"]), "objections": idx.get("objections"), "trials": idx.get("trials"),
                        "briefs": idx.get("briefs"),
                        "records": (ab or {}).get("corpus", {}).get("records"),
                        "works": (ab or {}).get("corpus", {}).get("distinct_works")} if ready else None),
            "families": (ab or {}).get("families") if ready else None,   # model families its runs used
            "lead": ({"id": lead["id"], "question": (lead.get("revision") or {}).get("research_question")
                      or lead["research_question"], "score": lead.get("score"), "outcome": lead.get("outcome"),
                      "novelty": lead.get("novelty"), "quality": lead.get("quality")} if lead else None),
            "searches": list((t.get("queries") or {}).keys()),
            # the full topic definition, so the site's "Start a topic" page can use any topic as a template
            "config": {k: t.get(k) for k in ("slug", "name", "description", "area", "queries", "fresh_from",
                                              "fresh_queries", "relevant", "relevance_levels", "schools")},
            "schools": t.get("schools", []),
            "config_path": f"config/topics/{slug}.yaml",
            "commands": topic_commands(slug),
        })
    topics.sort(key=lambda x: (x["status"] != "ready", not x["default"], x["name"]))   # explored first
    out = {"default": DEFAULT_TOPIC, "current_export": TOPIC_SLUG, "topics": topics}
    WEB_DATA_ROOT.mkdir(parents=True, exist_ok=True)
    (WEB_DATA_ROOT / "topics.json").write_text(json.dumps(out, ensure_ascii=False, indent=1))
    return out


UNGRADED_QUALITY = 0.6   # a direction the Assessor has not read counts as a middling 3/5


def latest_assessment(b: dict) -> dict | None:
    """The Assessor's most recent read: after the revision round if there was one."""
    return (b.get("revision") or {}).get("assessment") or b.get("assessment")


def normalize_run(run: dict) -> dict:
    """Export-time check of a stored run, so records written before the failure states existed cannot pass as
    results (fixed 2026-10-04): every novelty record gets an explicit status (a legacy failure path that stored
    1.0 becomes not assessed), and a trial saved as 'ok' without a Referee label for both defenders becomes
    failed, its stored outcome kept only as `legacy_outcome`. Model text and evidence are never changed."""
    from crux_lab.graph.schema import DEFENDERS, trial_complete
    from crux_lab.lab.novelty import normalize
    run["novelty"] = {k: normalize(v) for k, v in (run.get("novelty") or {}).items()}
    for t in run.get("trials", []):
        if t.get("status", "ok") == "ok" and not trial_complete(t):
            per = t.get("per_defender") or {}
            missing = [d for d in DEFENDERS if not per.get(d, {}).get("outcome")]
            t.update(status="failed", legacy_outcome=t.get("outcome"), outcome=None, revised_premise=None,
                     missing_labels=missing, normalized_at_export=True,
                     error=f"incomplete defender assessment: missing {', '.join(missing) or 'outcome'} "
                           "(found when exporting)")
    # the replayed event stream must say the same as the records
    trials = {t["id"]: t for t in run.get("trials", [])}
    for ev in run.get("events") or []:
        if ev.get("type") == "novelty" and ev.get("objection_id") in run["novelty"]:
            n = run["novelty"][ev["objection_id"]]
            ev.update(novelty=n.get("novelty"), status=n.get("status"), reason=n.get("reason", ""))
        elif ev.get("type") == "trial_end" and ev.get("trial_id") in trials:
            t = trials[ev["trial_id"]]
            if t.get("status") == "failed":
                ev.update(status="failed", outcome=None, error=t.get("error"),
                          missing_labels=t.get("missing_labels", []))
    return run


def brief_eligibility(runs: list[dict]) -> dict[str, str]:
    """objection id -> "" if its brief may be ranked, else why not."""
    from crux_lab.graph.schema import trial_complete
    from crux_lab.lab.novelty import is_assessed
    why: dict[str, str] = {}
    for run in runs:
        trials = {t["objection_id"]: t for t in run.get("trials", [])}
        for oid in set(trials) | set(run.get("novelty") or {}):
            t, n = trials.get(oid), (run.get("novelty") or {}).get(oid)
            why[oid] = ("trial incomplete" if not t or not trial_complete(t)
                        else "novelty not assessed" if not is_assessed(n) else "")
    return why


def rank_directions(briefs: list[dict]) -> list[dict]:
    """Lead score = survival × novelty × quality, best first.

    survival: how the objection fared against both defenders; novelty: 1 - closest prior art found; quality: the
    Assessor's latest overall score / 5 (after revision if any). One product, so a direction that is both new and
    sound leads, and a sound but already-published one or a new but incoherent one does not. `tier` is the
    direction's rank within its own paper (0 = that paper's best). A direction without an assessed novelty has
    no lead score and is left out of the ranking."""
    briefs = [b for b in briefs if b.get("novelty") is not None]
    for b in briefs:
        a = latest_assessment(b)
        b["quality"] = round(a["overall"] / 5, 3) if a and a.get("overall") is not None else None
        q = b["quality"] if b["quality"] is not None else UNGRADED_QUALITY
        b["score"] = round(b["survival"] * b["novelty"] * q, 4)
    out = sorted(briefs, key=lambda b: (-b["score"], -b["novelty"], b["id"]))
    seen: dict = {}
    for b in out:
        b["tier"] = seen.get(b["run_id"], 0)
        seen[b["run_id"]] = b["tier"] + 1
    return out


def tracing_summary() -> dict:
    """How many LLM calls were traced with MLflow (local sqlite store unless Databricks was configured)."""
    import sqlite3

    from crux_lab.config import ROOT
    from crux_lab.config import settings
    db = ROOT / "mlruns" / "mlflow.db"
    out = {"backend": "databricks" if settings.has("databricks") else "local MLflow (mlruns/)", "traces": None}
    if db.exists():
        try:
            out["traces"] = sqlite3.connect(db).execute("select count(*) from trace_info").fetchone()[0]
        except sqlite3.Error:
            pass
    return out


def _read(p):
    return json.loads(p.read_text()) if p.exists() else None


def _record(p: dict) -> dict:
    return {"id": p["id"], "title": p.get("title", ""), "authors": p.get("authors", [])[:6],
            "year": p.get("year"), "url": p.get("url") or "", "venue": p.get("venue"),
            "abstract": (p.get("abstract") or "")[:1800], "source": p.get("source"),
            "fresh": bool(p.get("fresh")), "published": p.get("publication_date")}


def paper_of_claim(cid: str) -> str:
    return cid.split(".", 1)[0]


def main() -> dict:
    out = WEB_DATA
    if Store().count(Claim) == 0:
        # A fresh clone has the committed export but not the (gitignored) claim store: never overwrite
        # the committed site data with an empty graph.
        raise SystemExit("export: the claim store (data/crux.sqlite) is empty — run `make map` first. "
                         "The committed web/public/data was left untouched.")
    if out.exists():
        for sub in ("runs", "briefs"):
            d = out / sub
            if d.exists():
                shutil.rmtree(d)
    (out / "runs").mkdir(parents=True, exist_ok=True)
    (out / "briefs").mkdir(parents=True, exist_ok=True)
    corpus = load_corpus()
    papers = {p["id"]: p for p in corpus}
    short = {p["id"].split(":", 1)[-1]: p["id"] for p in corpus}
    store = Store()
    needed: set[str] = set()

    runs_summary = []
    runs_all: list[dict] = []
    for f in sorted(RUNS.glob("run-*.json")):
        run = normalize_run(json.loads(f.read_text()))
        runs_all.append(run)
        needed.add(run["target"]["paper_id"])
        for n in run.get("novelty", {}).values():
            for m in n.get("matches", []):
                needed.add(m["paper_id"])
        for t in run.get("trials", []):
            for cid in t.get("cited_claim_ids", []):
                if paper_of_claim(cid) in short:
                    needed.add(short[paper_of_claim(cid)])
        (out / "runs" / f.name).write_text(json.dumps(run, ensure_ascii=False))
        outcomes: dict[str, int] = {}
        for t in run.get("trials", []):
            k = t.get("outcome") if t.get("status", "ok") == "ok" and t.get("outcome") else "failed"
            outcomes[k] = outcomes.get(k, 0) + 1
        runs_summary.append({
            "run_id": run["run_id"], "target_id": run["target"]["id"], "kind": run["target"].get("kind"),
            "title": run["target"]["title"], "paper_id": run["target"]["paper_id"],
            "argument_title": run["argument"].get("title"), "objections": len(run.get("objections", [])),
            "trials": len(run.get("trials", [])), "outcomes": outcomes, "briefs": run.get("briefs", []),
            "families": run.get("families_used", []), "stop_reason": run.get("stop_reason"),
            "finished_at": run.get("finished_at")})

    briefs = []
    eligibility = brief_eligibility(runs_all)
    held_back: list[dict] = []
    for f in sorted(BRIEFS.glob("brief-*.json")):
        b = json.loads(f.read_text())
        (out / "briefs" / f.name).write_text(json.dumps(b, ensure_ascii=False))
        md = f.with_suffix(".md")
        if md.exists():
            (out / "briefs" / md.name).write_text(md.read_text())
        for c in b.get("closest_literature", []):
            if c.get("paper_id"):
                needed.add(c["paper_id"])
        run_id = next((r["run_id"] for r in runs_summary if b["id"] in r["briefs"]), None)
        not_ok = eligibility.get(b.get("objection_id"), "no trial record")
        if not_ok:      # the brief file stays readable; it gets no lead score and is not listed
            held_back.append({"id": b["id"], "why": not_ok})
            continue
        briefs.append({"id": b["id"], "run_id": run_id, "research_question": b["research_question"],
                       "outcome": b.get("outcome"), "novelty": b["novelty"],
                       "records_searched": b["records_searched"],
                       "survival": SURVIVAL.get(b.get("outcome") or "", 0),
                       "paper_title": b["argument"].get("paper_title"),
                       "challenged_premise": b["challenged_premise"],
                       "paper_direction": b["paper_direction"],
                       "assessment": ({k: b["assessment"][k] for k in ("grade", "overall", "scores", "summary")}
                                      if b.get("assessment") else None),
                       "revision": ({"research_question": b["revision"]["research_question"],
                                     "paper_direction": b["revision"].get("paper_direction", ""),
                                     "assessment": ({k: b["revision"]["assessment"][k]
                                                     for k in ("grade", "overall", "scores", "summary")}
                                                    if b["revision"].get("assessment") else None)}
                                    if b.get("revision") else None)})
    briefs = rank_directions(briefs)
    (out / "briefs.json").write_text(json.dumps(briefs, ensure_ascii=False, indent=1))

    # claims + edges for the atlas (embeddings dropped)
    from crux_lab.corpus.dedup import work_of
    claims = [c.model_dump(exclude={"embedding"}) for c in store.all(Claim)]
    for c in claims:
        needed.add(c["paper_id"])
        c["work"] = work_of(c["paper_id"])   # same paper listed twice in OpenAlex -> same work
    args = [a.model_dump() for a in store.all(Argument)]
    edges = [e.model_dump() for e in store.edges()]
    (out / "claims.json").write_text(json.dumps({"claims": claims, "arguments": args, "edges": edges},
                                                ensure_ascii=False))
    live = {}
    from crux_lab.lab.novelty import LIVE_CACHE
    for f in LIVE_CACHE.glob("*.json") if LIVE_CACHE.exists() else []:
        for w in json.loads(f.read_text()):
            live.setdefault(w["id"], {**w, "source": "openalex_live"})
    records = {pid: _record(papers.get(pid) or live[pid]) for pid in sorted(needed) if pid in papers or pid in live}
    (out / "records.json").write_text(json.dumps(records, ensure_ascii=False))
    # Slim title index for /atlas (it shows titles and years only; the record drawer loads records.json).
    titles = {pid: {"id": pid, "title": r["title"], "year": r["year"]} for pid, r in records.items()}
    (out / "titles.json").write_text(json.dumps(titles, ensure_ascii=False, separators=(",", ":")))

    results = {k: _read(RESULTS / f"{k}.json") for k in ("e1", "e2", "e3")}
    (out / "results.json").write_text(json.dumps(results, ensure_ascii=False, indent=1))
    resolved = _read(TOPIC_RESOLVED) or _read(RESOLVED_MODELS) or {}
    targets = _read(TARGETS) or {}
    map_stats = _read(MAP_STATS) or {}
    about = {
        "topic": {k: TOPIC.get(k) for k in ("slug", "name", "description", "area")},
        "diversity": resolved.get("diversity"), "families": resolved.get("families", []),
        "roles": resolved.get("roles", {}),
        "models": [{k: m[k] for k in ("provider", "model", "family", "ok")} for m in resolved.get("models", [])],
        "targets_meta": targets.get("meta", {}),
        "map_stats": {k: map_stats.get(k) for k in ("fulltext_claims", "abstract_claims", "claims_indexed",
                                                   "abstracts_indexed", "embedder")},
        "corpus": {"records": len(corpus), "distinct_works": len(set(work_ids(corpus).values())),
                   "with_abstract": sum(1 for p in corpus if p.get("abstract")),
                   "full_texts": sum(1 for p in corpus if p.get("pdf_path")),
                   "fresh": sum(1 for p in corpus if p.get("fresh")),
                   "searches": list(TOPIC.get("queries", {})), "fresh_from": str(TOPIC.get("fresh_from", ""))},
    }
    tot: dict[str, int] = {}
    for r in runs_summary:
        for k, v in r["outcomes"].items():
            tot[k] = tot.get(k, 0) + v
    never = [o for o in ("rebutted", "standing", "known_answer") if not tot.get(o)]
    skew = ("Outcome distribution across all trials: " + ", ".join(f"{k} {v}" for k, v in sorted(tot.items(), key=lambda kv: -kv[1]))
            + (f". No trial ended {' or '.join(never)}: defenders usually save the argument by narrowing a premise, "
               "which counts as revision_required, so read it as 'this premise needs work', not as a defeated argument."
               if never else "."))
    n_works = len(set(work_ids(corpus).values()))
    dup_note = (f"OpenAlex lists some papers more than once (versions, preprint + article): the {len(corpus)} corpus "
                f"records are {n_works} distinct works. 'Records searched' counts records; nearest matches, the "
                "prior-art search box and E1 are scored per distinct work.")
    about["method_notes"] = METHOD_NOTES + ([skew] if tot else []) + [dup_note] + (
        [f"{len(held_back)} brief(s) are not ranked because their trial is incomplete or their novelty was not "
         "assessed: " + "; ".join(f"{h['id']} ({h['why']})" for h in held_back)] if held_back else [])
    about["tracing"] = tracing_summary()
    (out / "about.json").write_text(json.dumps(about, ensure_ascii=False, indent=1))
    index = {"generated_at": datetime.now(timezone.utc).isoformat(), "runs": runs_summary,
             "targets": targets.get("targets", []), "briefs": len(briefs),
             "trials": sum(r["trials"] for r in runs_summary),
             "objections": sum(r["objections"] for r in runs_summary),
             "headline": headline(results, runs_summary, briefs)}
    (out / "index.json").write_text(json.dumps(index, ensure_ascii=False, indent=1))
    write_topics_index()
    print(f"exported {len(runs_summary)} runs, {len(briefs)} briefs, {len(claims)} claims, "
          f"{len(records)} records -> {out}")
    return index


def headline(results: dict, runs: list[dict], briefs: list[dict]) -> list[dict]:
    """Three landing-page numbers, each computed from files (never typed in by hand)."""
    h = []
    trials = sum(r["trials"] for r in runs)
    surv = sum(r["outcomes"].get("standing", 0) + r["outcomes"].get("revision_required", 0) for r in runs)
    if trials:
        h.append({"label": "objections still standing or forcing a revision after both defenders",
                  "value": f"{surv}/{trials}", "source": "data/runs"})
    e1 = results.get("e1") or {}
    if e1.get("methods"):
        best = max(e1["methods"], key=lambda m: m.get("recall_at_5", 0))
        h.append({"label": f"prior-art recall@5 ({best['name']})", "value": f"{best['recall_at_5']:.0%}",
                  "source": "results/e1.json"})
    e2 = results.get("e2") or {}
    if e2.get("misreading", {}).get("n"):
        h.append({"label": "deliberate misreadings caught by the Referee",
                  "value": f"{e2['misreading']['caught']}/{e2['misreading']['n']}", "source": "results/e2.json"})
    if len(h) < 3 and briefs:
        h.append({"label": "research briefs ready for human review", "value": str(len(briefs)),
                  "source": "data/briefs"})
    return h[:3]
